services:
  jappy:
    platform: linux/amd64 # descomente si el procesador es Intel o AMD.
    #platform: linux/arm64 # descomente si el procesador es ARM.
    
    image: gastudil/courses:jappy-latest
    container_name: dev-jappy
    hostname: dev-jappy
    ports:
      - 8888:8888
    volumes:
      - ./workspace:/home/devuser/workspace
    networks:
      - back_net

networks:
  back_net:
