@startuml
start

:Inicio;
:Paso 1;
if (¿Condición?) then (Sí)
    :Paso 2;
else (No)
    :Paso 3;
endif

:Paso 4;

while (¿Condición?)
    : Paso5;
    : Paso6;
endwhile

: Paso 7;
: Paso 8;
stop
@enduml